/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\other.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/other.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[1.693, -0.875, -1.002]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials.WheelIn} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials.WheenOut} />
      </group>
      <mesh geometry={nodes.Plane.geometry} material={materials.ColorRed} position={[1.569, -0.767, -0.85]} />
    </group>
  )
}

useGLTF.preload('/other.glb')
